const MSG = { 
    START_GAME: 'START_GAME', // Anfrage nach Game-Start
    GAME_STARTED: 'GAME_STARTED', // Antwort vom Gegner, jetzt gehts erst los
    SEND_GAME_CONTROL_MSG : 'SEND_GAME_CONTROL_MSG',
    RECEIVE_GAME_CONTROL_MSG : 'RECEIVE_GAME_CONTROL_MSG',
    SEND_CHAT_MSG : 'SEND_CHAT_MSG',
    RECEIVE_CHAT_MSG : 'RECEIVE_CHAT_MSG',
    SEND_GAME_DATA : 'SEND_GAME_DATA',
    RECEIVE_GAME_DATA : 'RECEIVE_GAME_DATA',
    SET_LEFT_PADDLE : 'SET_LEFT_PADDLE',
    SET_RIGHT_PADDLE : 'SET_RIGHT_PADDLE',
    MOVE_LEFT_PADDLE : 'MOVE_LEFT_PADDLE',
    MOVE_RIGHT_PADDLE : 'MOVE_RIGHT_PADDLE',
    MOVE_BALL : 'MOVE_BALL',
    MOVE_OBJECT : 'MOVE_OBJECT',
    CONN_INDEX_ERR: -1
};

module.exports = MSG;
